version: 2
jobs: 
  build:
    branches:
      only: master
    docker:
      - image: node:10.15.1
      - image: nginx:alpine
      # - image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      #   aws_auth:
      #     aws_access_key_id: $AWS_ACCESS_KEY_ID
      #     aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    working_directory: /usr/src/www
    steps: 
      - checkout
      - setup_remote_docker
      
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      
      - run:
          name: Build the docker image and tag
          command: |
            docker build -t $IMAGE_NAME .
            docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
            docker push $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest